project:
  type: website

website:
  title: "Haal01"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: Hobbies.qmd
        text: My Hobbies
      - href: projects.qmd
        text: My Projects

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

